# Generic functions that GUI classes can attach to

# convenience for interacting with the hub
setGeneric("getModule", function(gui, hub, id) standardGeneric("getModule"))
setGeneric("getWidget", function(gui, hub, id) standardGeneric("getWidget"))
setGeneric("setWidgets", function(gui, hub, ...) standardGeneric("setWidgets"))
setGeneric("getSetting", function(gui, hub, id) standardGeneric("getSetting"))

# making the gui
setGeneric("makeGUI", function(gui, hub) standardGeneric("makeGUI"))
setGeneric("destroyGUI", function(gui, hub) standardGeneric("destroyGUI"))
setGeneric("remakeGUI", function(gui, hub, show = TRUE) standardGeneric("remakeGUI"))
setGeneric("showGUI", function(gui, hub) standardGeneric("showGUI"))
setGeneric("hideGUI", function(gui, hub) standardGeneric("hideGUI"))

# specific functions streamlining GUI design but that are not intended to be derived
setGeneric("getNavigationXML", function(gui, hub) standardGeneric("getNavigationXML"))
setGeneric("makeNavigation", function(gui, hub) standardGeneric("makeNavigation"))
setGeneric("makeInfoBar", function(gui, hub) standardGeneric("makeInfoBar"))

# getting and setting key widgets
setGeneric("getWindow", function(gui, hub) standardGeneric("getWindow"))
setGeneric("getWinGroup", function(gui, hub) standardGeneric("getWinGroup"))
setGeneric("setMenuGroup", function(gui, hub, menuGroup) standardGeneric("setMenuGroup"))
setGeneric("setToolbarGroup", function(gui, hub, toolbarGroup) standardGeneric("setToolbarGroup"))

# functions that are intended to be extended in GUI derived classes
setGeneric("getMenuXML", function(gui, hub) standardGeneric("getMenuXML"))
setGeneric("getToolbarXML", function(gui, hub) standardGeneric("getToolbarXML"))
setGeneric("makeMainGUI", function(gui, hub) standardGeneric("makeMainGUI"))
setGeneric("setNavigationActions", function(gui, hub, actionGrp) standardGeneric("setNavigationActions"))

# other utility functions for interacting with the GUI
setGeneric("showInfo", function(gui, hub, msg, type="question", timer=2, okButton=TRUE) standardGeneric("showInfo"))
setGeneric("hideInfo", function(gui, hub) standardGeneric("hideInfo"))

#########
# Class #
#########

# S4 class GUI
GUI <- setClass("GUI", representation = list(module="character")) # which module this belongs to, is automatically set by the hub

setMethod("initialize", "GUI", function(.Object, ...) {
  callNextMethod(.Object, ...)
})

###################
# general Methods #
###################

setMethod("makeGUI", "GUI", function(gui, hub) {
  cat("I am a", class(gui), "and have module", gui@module, "and I am making my GUI.\n")
  options("guiToolkit"="RGtk2") # everything is written in RGtk2
  
  cat("\tGUI settings are as follows:\n")
  
  # make window
  win <- gwindow(
    getSetting(gui, hub, "windowTitle"), visible=FALSE, 
    width=getSetting(gui, hub, "windowSize")[1], 
    height=getSetting(gui, hub, "windowSize")[2])
  
  # destroy window properly
  addHandlerDestroy(win, function(h,...) {
      cat(paste0("Window for ", class(gui), " (module ", gui@module,") is being destroyed! Cleaning all widgets in the module.\n"))
      getModule(gui, hub)$cleanWidgets() # clean all widget references
    }) # clean widgets
  
  # save window in hub
  setWidgets(gui, hub, window = win)
  
  # top window group
  baseGroup <- ggroup(horizontal=FALSE, expand=TRUE, cont = win, spacing=0) # contains only the winGroup and the infobar
  parent <- getToolkitWidget(baseGroup)$getParent() # get automatic toplevel gtkHBox generated by gwindow
  parent['border-width']<-0 # remove border
  setWidgets(gui, hub, 
    baseGroup = baseGroup,
    winGroup = ggroup(horizontal=FALSE, expand=TRUE, cont = baseGroup, spacing=0))
  
  # make info bar
  makeInfoBar(gui, hub)
  
  # main make GUI
  makeMainGUI(gui, hub)
  makeNavigation(gui, hub)
})

setMethod("destroyGUI", "GUI", function(gui, hub) {
  cat("I am a", class(gui), "and have module", gui@module, "and I am destroying my GUI.\n")
  dispose(getWindow(gui, hub)) # destroy window
  getModule(gui, hub)$cleanWidgets() # clean all widget references
})

setMethod("remakeGUI", "GUI", function(gui, hub, show = TRUE) {
  destroyGUI(gui, hub)
  makeGUI(gui, hub)
  if (show)
    showGUI(gui, hub)
})

setMethod("showGUI", "GUI", function(gui, hub) {
  cat("I am a", class(gui), "and have module", gui@module, "and I am showing my GUI.\n")
  if (is.null(getWindow(gui, hub)))
    makeGUI(gui, hub)
  visible(getWindow(gui, hub), TRUE)
})

setMethod("hideGUI", "GUI", function(gui, hub) {
  cat("I am a", class(gui), "and have module", gui@module, "and I am hiding my GUI.\n")
  if (!is.null(getWindow(gui, hub)))
    visible(getWindow(gui, hub), FALSE)
})

################################
# methods for streamlining GUI #
################################

setMethod("getNavigationXML", "GUI", function(gui, hub) {
  return(paste(
    '<ui>',
      '<menubar name="menubar">',
        getMenuXML(gui, hub),      
      '</menubar>',
      '<toolbar name ="toolbar">',
        getToolbarXML(gui, hub),
      '</toolbar>',
    '</ui>', sep="\n"))
})

setMethod("makeNavigation", "GUI", function(gui, hub) {
  
  # navigation actions
  cat("\tInitializing Navigation.\n")
  setWidgets(gui, hub, actionGroup = gtkActionGroup ("FileGroup"))
  cat("\tSetting Navigation Actions.\n")
  setNavigationActions(gui, hub, getWidget(gui, hub, 'actionGroup'))
  
  # UI manager for navigation
  cat("\tMaking Navigation Manager.\n")
  uimanager <- gtkUIManagerNew() # ui manager
  uimanager$insertActionGroup (getWidget(gui, hub, 'actionGroup'), 0) # add actions
  uimanager$addUiFromString (getNavigationXML(gui, hub)) # add ui 
  
  # menu
  menuGrp <- getWidget(gui, hub, 'menuGroup')
  if (!is.null(menuGrp)) {
    cat("\tMaking Menubar.\n")
    getToolkitWidget(menuGrp)$packStart (uimanager$getWidget ("/menubar"), FALSE ) # add menu
  }
    
  # toolbar
  toolbarGrp <- getWidget(gui, hub, 'toolbarGroup')
  if (!is.null(toolbarGrp)) {
    getToolkitWidget(toolbarGrp)$packStart (uimanager$getWidget ( "/toolbar" ), FALSE) # add toolbar
    cat("\tMaking Toolbar.\n")
  }
  getToolkitWidget(getWindow(gui, hub))$addAccelGroup (uimanager$getAccelGroup()) # add keyboard triggers
  
})

setMethod("makeInfoBar", "GUI", function(gui, hub){
  infoBar <- gtkInfoBar (show=FALSE) 
  infoBar$setNoShowAll(TRUE)
  infoLabel <- gtkLabel ( "Warning , Warning")
  infoBar$setMessageType("question") 
  infoBar$getContentArea()$add(infoLabel)
  infoOkButton <- infoBar$addButton(button.text = "gtk-ok", response.id = GtkResponseType['ok'])
  gSignalConnect(infoBar, "response", function(infoBar, resp.id) hideInfo(gui, hub))
  getToolkitWidget(getWidget(gui, hub, "baseGroup"))$packStart(infoBar, expand=FALSE)
  setWidgets(gui, hub, infoBar = infoBar, infoLabel = infoLabel, infoOkButton = infoOkButton)
})


#' show an info message
#' type - styling of the mssage, info, error, question, warning are the standard ones
#' timer - time in seconds until message disappears automatically
#' okButton - whether there is an ok button or not
setMethod("showInfo", "GUI", function(gui, hub, msg, type="question", timer=2, okButton=TRUE) {
  cat("\tShowing info message for", timer, "seconds.\n")
  getWidget(gui, hub, 'infoBar')$setMessageType(type)
  getWidget(gui, hub, 'infoLabel')$setText(msg)
  getWidget(gui, hub, 'infoBar')$show()
  if (!okButton)
    getWidget(gui, hub, 'infoOkButton')$hide()  
  else
    getWidget(gui, hub, 'infoOkButton')$show()
  if (!is.null(timer)) {
    Sys.sleep(timer)
    hideInfo(gui, hub)
   }
})

# hide info bar
setMethod("hideInfo", "GUI", function(gui, hub) {
  cat("\tHiding info message.\n")
  getWidget(gui, hub, 'infoBar')$hide()
})


############################################
# methods that are supposed to be extended #
############################################

setMethod("getMenuXML", "GUI", function(gui, hub) { return('') })

setMethod("getToolbarXML", "GUI", function(gui, hub) { return('') })

setMethod("makeMainGUI", "GUI", function(gui, hub) {})

setMethod("setNavigationActions", "GUI", function(gui, hub, actionGrp) { })

######################################################
# Convenience functions for interacting with the hub #
######################################################

setMethod("getModule", "GUI", function(gui, hub) {
  return(hub$getModule(gui@module))
})

setMethod("getWidget", "GUI", function(gui, hub, id) {
  return(getModule(gui, hub)$getWidget(id))
})

setMethod("setWidgets", "GUI", function(gui, hub, ...) {
  return(getModule(gui, hub)$setWidgets(...))
})

setMethod("getSetting", "GUI", function(gui, hub, id) {
  return(getModule(gui, hub)$getSetting(id))
})

#FIXME: implement setSettings!

###################################
# Getting and Setting key widgets #
###################################

setMethod("getWindow", "GUI", function(gui, hub) {
  return(getWidget(gui, hub, "window"))
})

setMethod("getWinGroup", "GUI", function(gui, hub) {
  return(getWidget(gui, hub, "winGroup"))
})

setMethod("setMenuGroup", "GUI", function(gui, hub, menuGroup) {
  setWidgets(gui, hub, menuGroup = menuGroup)
})

setMethod("setToolbarGroup", "GUI", function(gui, hub, toolbarGroup) {
  setWidgets(gui, hub, toolbarGroup = toolbarGroup)
})


##################
# Info messaging #
##################


