guiDataManager <- function(module, hub) {
  # setup toplevel widgets
  wingrp<-ggroup(horizontal=FALSE, expand=TRUE, cont=module$widgets$win, spacing=0)
  parent <- getToolkitWidget(wingrp)$getParent() # get automatic toplevel gtkHBox generated by gwindow
  parent['border-width']<-0 # remove border
  
  # top level groups
  glabel("Data Manager", cont=wingrp)
  gbutton("Hub", cont=wingrp, handler=function(...) {
    hub$launchHub()
  })
  
  message(class(hub))
}