# S4 class HubGUI
HubGUI <- setClass("HubGUI", contains="GUI")


guiHub <- function(module, hub) {
  # setup toplevel widgets
  wingrp<-ggroup(horizontal=FALSE, expand=TRUE, cont=module$widgets$win, spacing=0)
  parent <- getToolkitWidget(wingrp)$getParent() # get automatic toplevel gtkHBox generated by gwindow
  parent['border-width']<-0 # remove border
  
  # top level groups
  navgrp <- ggroup(horizontal=FALSE, cont=wingrp, spacing=0)
  maingrp <- ggroup(horizontal=TRUE, container=wingrp, expand=TRUE)
  lg <- ggroup(horizontal=FALSE, container=maingrp, expand=TRUE)
  lr <- ggroup(horizontal=FALSE, container=maingrp, expand=TRUE)
  
  # menu
  nav.xml<-'<ui>
  <menubar name="menubar">
  <menu name = "CSIDE" action="CSIDE">
  <menuitem action="Help"/>
  <menuitem action="Quit" />
  </menu>
  </menubar>
  </ui>'
  nav.actions <-
    list(## name, icon, label , accelerator , tooltip , callback
      list ("CSIDE" , NULL , "_CSIDE" , NULL , NULL , NULL ) ,
      list ("Help" , "gtk-info" ,"Help" , "<ctrl>H" , NULL , function(...) gmessage("sorry, not implemented yet") ) ,
      list ("Quit", "gtk-quit", "Quit", "<ctrl>Q", "Quit program", function(...) guiQuit(module, hub) ))
  actionGrp <- gtkActionGroup ( "FileGroup" )
  actionGrp$addActions(nav.actions)
  
  uimanager <- gtkUIManagerNew() # ui manager
  uimanager$insertActionGroup (actionGrp, 0) # add actions
  uimanager$addUiFromString (nav.xml) # add ui 
  getToolkitWidget(navgrp)$packStart (uimanager$getWidget ("/menubar"), FALSE ) # add menu
  getToolkitWidget(module$widgets$win)$addAccelGroup (uimanager$getAccelGroup ( )) # add keyboard triggers
  
  # launcher group
  addSpring(lr)
  glayout <- glayout(anchor=c(0,0), container=lr, expand=TRUE)
  glayout[1,2] <- gbutton(action=gaction("DSQDP", icon="gtk-select-color", handler=function(...) hub$launchDataManager()), cont=glayout)
  glayout[1,5] <- gbutton(action=gaction("IDP", icon="plot", handler=function(...) print("test")), cont=glayout)
  glayout[2,1:3] <- "Isotope Data Manager"
  glayout[2,4:6] <- "Isodat File Parser"
  addSpring(lr)
}

CSIDE.init <- function (sourceCode, modal) {
  library(gWidgets)
  library(RGtk2)
  options("guiToolkit"="RGtk2")
  
  # start window and top level group (remove border for menu)
  gw <- win.init("CSIDE", width=400, height=400, modal=modal)
  wingrp<-ggroup(horizontal=FALSE, expand=TRUE, cont=gw, spacing=0)
  if (modal)
    parent <- getToolkitWidget(wingrp) # get automatic toplevel gtkHBox generated by dialog
  else
    parent <- getToolkitWidget(wingrp)$getParent() # get automatic toplevel gtkHBox generated by gwindow
  parent['border-width']<-0 # remove border
  
  # set window position to center
  gtkWindowSetPosition(getToolkitWidget(gw), GtkWindowPosition[2])
  
  # top level groups
  navgrp <- ggroup(horizontal=FALSE, cont=wingrp, spacing=0)
  maingrp <- ggroup(horizontal=TRUE, container=wingrp, expand=TRUE)
  lg <- ggroup(horizontal=FALSE, container=maingrp, expand=TRUE)
  lr <- ggroup(horizontal=FALSE, container=maingrp, expand=TRUE)
  
  # menu
  nav.xml<-'<ui>
  <menubar name="menubar">
  <menu name = "CSIDE" action="CSIDE">
  <menuitem action="Help"/>
  <menuitem action="Quit" />
  </menu>
  </menubar>
  </ui>'
  nav.actions <-
    list(## name, icon, label , accelerator , tooltip , callback
      list ("CSIDE" , NULL , "_CSIDE" , NULL , NULL , NULL ) ,
      list ("Help" , "gtk-info" ,"Help" , "<ctrl>H" , NULL , function(...) gmessage("sorry, not implemented yet") ) ,
      list ("Quit", "gtk-quit", "Quit", "<ctrl>Q", "Quit program", function(...) dispose(gw) ))
  actionGrp <- gtkActionGroup ( "FileGroup" )
  actionGrp$addActions(nav.actions)
  
  uimanager <- gtkUIManagerNew() # ui manager
  uimanager$insertActionGroup (actionGrp, 0) # add actions
  uimanager$addUiFromString (nav.xml) # add ui 
  getToolkitWidget(navgrp)$packStart (uimanager$getWidget ("/menubar"), FALSE ) # add menu
  getToolkitWidget(gw)$addAccelGroup (uimanager$getAccelGroup ( )) # add keyboard triggers
  
  
  #FIXME - implement screen
  # this is the control center
  # modal dialogs return fixed values wherever they come from and
  # an order where to pass this onward to (or no orders at all)
  
  # screen layout
  # folder browser on the left (just a simple tree that starts in the starting WD)
  # can select any folder (fold/unfold setup) and get an info message whether there is already something in there?
  # with a folder selected, can click on either Data Manager or Hydrogen Data Module or (later Chromparse) and it
  # will load that workspace
  # --> make sure to resource code everytime!
  
  print(getwd())
  cat("\n\n")
  
  # file browser
  fileBrowser.items <- function(path = NULL, user.data=NULL) {
    if (is.null(path)) 
      path <- getwd()
    else
      path <- file.path(getwd(), do.call("file.path", args=as.list(path)))
    
    folders <- subset(data.frame(
      Folder=dir(path=path, include.dirs=TRUE),
      Path=dir(path=path, include.dirs=TRUE, full.names=TRUE),
      file.info(dir(path=path, include.dirs=TRUE, full.names=TRUE))[,c(1:2)], 
      stringsAsFactors=FALSE), isdir==TRUE)
    
    #FIXME: check what is going on here with the subdirectory...
    
    #print(folders)
    return(folders)
  }
  
  # check for subfolders
  fileBrowser.hasOffspring <- function(children, user.data=NULL, ...) return(children$isdir) # which items have subdirectories
  fileBrowser.icons <- function(children,user.data=NULL, ...) return(rep("gtk-directory", length=nrow(children))) # FIXME: could implement some indicator which folders have already been used
  
  tree <- gtree(fileBrowser.items, fileBrowser.hasOffspring, icon.FUN = fileBrowser.icons, container=lg, expand=TRUE, handler=function(h,...) print("hello"))
  
  #   fileBrowser.gui<-function() {
  #     if (!is.null(tag(idp$gui$win, "fileBrowserGrp")))
  #       delete(tag(idp$gui$win, "fileBrowserParentGrp"), tag(idp$gui$win, "fileBrowserGrp"))
  #     tag(idp$gui$win, "fileBrowserGrp") <- ggroup(expand=TRUE)
  #     add(tag(idp$gui$win, "fileBrowserParentGrp"), tag(idp$gui$win, "fileBrowserGrp"), expand=TRUE)
  #     tree<-gtree(fileBrowser.items, fileBrowser.hasOffspring, icon.FUN = fileBrowser.icons, container=tag(idp$gui$win, "fileBrowserGrp"), expand=TRUE, handler=function(h,...) {
  #       if (is.null(subpath <- svalue(h$obj[]))) { 
  #         path <- IDP.getSettings(idp, "fileDirectory")
  #         file <- svalue(h$obj)
  #       } else {
  #         print(subpath)
  #         path <- file.path(IDP.getSettings(idp, "fileDirectory"), do.call("file.path", args=as.list(subpath[-length(subpath)])))
  #         file <- subpath[length(subpath)]
  #       }
  #       
  #       newpath <- file.path(path, file) # assemble new path  
  #       if (identical(file, "...")) { # except: top level directory
  #         pathparts <- strsplit(path, .Platform$file.sep)[[1]]
  #         newpath <- do.call("file.path", args=as.list(pathparts[-length(pathparts)]))
  #       } 
  #       
  #       if (file.info(newpath)$isdir) { # open directory
  #         IDP.setSettings(idp, list(fileDirectory = newpath))
  #         fileBrowser.gui()
  #       } else # open file
  #         IDP.openIsodatFile(idp, path, file)
  #     })
  #   }
  
  # launcher group
  addSpring(lr)
  glayout <- glayout(anchor=c(0,0), container=lr, expand=TRUE)
  glayout[1,2] <- gbutton(action=gaction("DSQDP", icon="gtk-select-color", handler=function(...) print("test")), cont=glayout)
  glayout[1,5] <- gbutton(action=gaction("IDP", icon="plot", handler=function(...) print("test")), cont=glayout)
  glayout[2,1:3] <- "Isotope Data Manager"
  glayout[2,4:6] <- "Isodat File Parser"
  addSpring(lr)
  
  
  # make visible
  cat("\nWelcome to CSIDE. Have fun!\n\n")
  visible(gw, TRUE)
}
