# S4 class HubGUI
HubGUI <- setClass("HubGUI", contains="GUI")

setMethod("getMenuXML", "HubGUI", function(gui, hub) {
  return (
    '<menu name = "CSIDE" action="CSIDE">
      <menuitem action="Help"/>
      <menuitem action="Reload"/>
      <menuitem action="Quit" />
    </menu>')
})

setMethod("getToolbarXML", "HubGUI", function(gui, hub) {
  nav <- '<separator expand="true"/>'
  for (name in names(hub$modules)) # add all modules to toolbar
    if (name!='hub')
      nav <- paste0(nav, '<toolitem action="Module', name,'"/>')
  return (paste0(nav, '<separator expand="true"/>'))
})

setMethod("setNavigationActions", "HubGUI", function(gui, hub, actionGrp) {
  nav.actions <-
    list(## name, icon, label , accelerator , tooltip , callback
      list ("CSIDE" , NULL , "_CSIDE" , NULL , NULL , NULL ) ,
      list ("Help" , "gtk-info" ,"Help" , "<ctrl>H" , NULL , function(...) gmessage("sorry, not implemented yet") ) ,
      list ("Reload" , "gtk-refresh" ,"Reload Screen" , "<ctrl>R" , NULL , function(...) remakeGUI(gui, hub) ) , # FIXME: disable the keyboard shortcut!
      list ("Quit", "gtk-quit", "Quit", "<ctrl>Q", "Quit program", function(...) destroyGUI(gui, hub) ))
  
  # add module launch actions to toolbar
  for (name in names(hub$modules)) {
    if (name!='hub') {
      nav.actions <- c(nav.actions, list(
        list(paste0("Module", name), # action handle
             hub$getModule(name)$getSetting("launchIcon"), # icon
             hub$getModule(name)$getSetting("launchName"), # label
             NULL, # short cut
             hub$getModule(name)$getSetting("launchTooltip"), # tooltip
             function(...) hub$launchModule(name)))) # launch module
    }
  }
  print(nav.actions)
  actionGrp$addActions(nav.actions)
})

setMethod("makeMainGUI", "HubGUI", function(gui, hub) {
  # setup toplevel widgets
  wingrp<-ggroup(horizontal=FALSE, expand=TRUE, cont=getWindow(gui, hub), spacing=0)
  parent <- getToolkitWidget(wingrp)$getParent() # get automatic toplevel gtkHBox generated by gwindow
  parent['border-width']<-0 # remove border

  # top level groups
  setMenuGroup(gui, hub, ggroup(horizontal=FALSE, cont=wingrp, spacing=0))
  mainGrp <- ggroup(horizontal=FALSE, cont=wingrp, spacing=0, expand=TRUE)
  setToolbarGroup(gui, hub, ggroup(horizontal=FALSE, cont=wingrp, spacing=0))
  
  
  
  
})

