#######################################
# Code for isodat file parser (IDP)   #
# User Interface (GUI)                #
# Copyright 2013 Sebastian Kopf       #
# seb.kopf@gmail.com                  #
#######################################

##################
# Info messaging #
##################

# show an info message
# type - styling of the mssage, info, error, question, warning are the standard ones
# timer - time in seconds until message disappears automatically
# okButton - whether there is an ok button or not
IDP.showInfo<-function(idp, msg, type="question", timer=2, okButton=TRUE) {
  idp$gui$infoBar$setMessageType(type)
  idp$gui$infoLabel$setText(msg)
  idp$gui$infoBar$show()
  if (!okButton)
    idp$gui$infoOkButton$hide()  
  else
    idp$gui$infoOkButton$show()
  if (!is.null(timer)) {
    Sys.sleep(timer)
    IDP.hideInfo(idp)
  }
}

# hide info bar
IDP.hideInfo<-function(idp) {
  idp$gui$infoBar$hide()
}

############
# Main GUI #
############

# launch the user interface
IDP.gui<-function(idp) { 

  ### storing settings for easier modification
  tag(idp$gui$win, "settings")<-idp$settings
  
  ### major divisions
  wingrp<-ggroup(horizontal=FALSE, expand=TRUE, cont=idp$gui$win, spacing=0)
    if (idp$gui$modal)
      parent <- getToolkitWidget(wingrp) # get automatic toplevel gtkHBox generated by dialog
    else
      parent <- getToolkitWidget(wingrp)$getParent() # get automatic toplevel gtkHBox generated by gwindow
    parent['border-width']<-0 # remove border
  idp$gui$navgrp<-ggroup(horizontal=FALSE, cont=wingrp, spacing=0) # navigation group
    # left top
    glt<-ggroup(horizontal=FALSE, expand=TRUE) # left column file browser group
    # left bottom
    glb<-ggroup(horizontal=FALSE, expand=TRUE) # left column for file info
      glbGTK<-getToolkitWidget(glb) # gtk object
      glbGTK['border-width']<-5 # border with
    # right top
    grt<-ggroup(horizontal=TRUE, expand=TRUE) # right top
      plot.grp<-ggroup(horizontal=FALSE, expand=TRUE, container=grt) # plot grp in right top
    # right bottom
    grb<-ggroup(horizontal=TRUE, expand=TRUE) # right bottom
      tag(idp$gui$win, "tableGrp")<-ggroup(horizontal=FALSE, expand=TRUE, container=grb) # table grp in bottom right
  idp$gui$gl<-gpanedgroup(glt, glb, horizontal=FALSE, expand=TRUE) # left column
  idp$gui$gr<-gpanedgroup(grt, grb, horizontal=FALSE, expand=TRUE) # right column
  idp$gui$gall<-gpanedgroup(idp$gui$gl, idp$gui$gr, horizontal=TRUE, container=wingrp, expand=TRUE) # total window group
  
  ### files browser
  tag(idp$gui$win, "fileBrowserParentGrp")<-glt
  tag(idp$gui$win, "fileBrowserGrp")<-NULL

  # all the items of the file browser
  fileBrowser.items <- function(path = NULL, user.data=NULL) {
    topleveldir <- is.null(path)
    if (topleveldir) 
      path <- tag(idp$gui$win, "settings")$fileDirectory # start with file directory from the settings
    files <- file.info(dir(path=path, full.names=TRUE))[,c(1,2,3)] # get all files and folders
    files <- data.frame(Name=dir(path=path), Dir=files[,2], stringsAsFactors=FALSE)
    files <- files[union(which(files$Dir), grep("\\.cf$", files$Name)),] # only folders and .cf files
    files <- files[order(-files$Dir, files$Name),] # sort by folder vs file and then name
    if (topleveldir) # add "..." at the beginning (FIXME: could make sure that it's not added if at root but too lazy now)
      files <- rbind(data.frame(Name="...", Dir=FALSE), files)
    return(files)
  }
  
  # functions to determine which items have sub items and which icons to use
  fileBrowser.hasOffspring <- function(children,user.data=NULL, ...)return(children$Dir) # which items have subdirectories
  fileBrowser.icons <- function(children,user.data=NULL, ...) {
    x <- rep("gtk-new", length=nrow(children))
    x[which(children$Name=="...")] <- "gtk-directory" # top level folder
    x[children$Dir] <- "gtk-directory" # real folders
    return(x)
  }
  
  # function to remake the file tree when switching folders (FIXME: somehow looses ability for tree expansion...maybe something about how the tree is added?)
  fileBrowser.gui<-function() {
    if (!is.null(tag(idp$gui$win, "fileBrowserGrp")))
      delete(tag(idp$gui$win, "fileBrowserParentGrp"), tag(idp$gui$win, "fileBrowserGrp"))
    tag(idp$gui$win, "fileBrowserGrp") <- ggroup(expand=TRUE)
    add(tag(idp$gui$win, "fileBrowserParentGrp"), tag(idp$gui$win, "fileBrowserGrp"), expand=TRUE)
    tree<-gtree(fileBrowser.items, fileBrowser.hasOffspring, icon.FUN = fileBrowser.icons, container=tag(idp$gui$win, "fileBrowserGrp"), expand=TRUE, handler=function(h,...) {
      if (is.null(subpath <- svalue(h$obj[]))) { 
        path <- IDP.getSettings(idp, "fileDirectory")
        file <- svalue(h$obj)
      } else {
        path <- file.path(IDP.getSettings(idp, "fileDirectory"), do.call("file.path", args=as.list(subpath[-length(subpath)])))
        file <- subpath[length(subpath)]
      }
      
      newpath <- file.path(path, file) # assemble new path  
      if (identical(file, "...")) { # except: top level directory
        pathparts <- strsplit(path, .Platform$file.sep)[[1]]
        newpath <- do.call("file.path", args=as.list(pathparts[-length(pathparts)]))
      } 
        
      if (file.info(newpath)$isdir) { # open directory
        IDP.setSettings(idp, list(fileDirectory = newpath))
        fileBrowser.gui()
      } else # open file
        IDP.openIsodatFile(idp, path, file)
    })
  }
  # --> file browser initialization is at the end because it needs other idp objects to be fully initialized
  
  ### file info group
  idp$gui$fileInfo<-list()
  idp$gui$fileInfo.nb<-gnotebook(cont = glb, expand=TRUE)
  fileInfo.layout <- glayout(cont = idp$gui$fileInfo.nb, expand=TRUE, label="File Info")
  fileInfo.layout[1, 1] <- "File:"
  fileInfo.layout[1, 2] <- (idp$gui$fileInfo$Filename <- glabel("", cont=fileInfo.layout))
  fileInfo.layout[2, 1] <- "GC:"
  fileInfo.layout[2, 2] <- (idp$gui$fileInfo$GCprogram <- glabel("", cont=fileInfo.layout))
  fileInfo.layout[3, 1] <- "AS:"
  fileInfo.layout[3, 2] <- (idp$gui$fileInfo$ASprogram <- glabel("", cont=fileInfo.layout))
  fileInfo.layout[4, 1] <- "MS:"
  fileInfo.layout[4, 2] <- (idp$gui$fileInfo$MSprogram <- glabel("", cont=fileInfo.layout))
  fileInfo.layout[5, 1] <- "H3:"
  fileInfo.layout[5, 2] <- (idp$gui$fileInfo$H3factor <- glabel("", cont=fileInfo.layout))
  
  ### file graph
  idp$gui$info.graph <- ggraphics(container=idp$gui$fileInfo.nb, label="Refs", expand=TRUE)
  
  ### plot grp
  idp$gui$pn <- pn.GUI(plot.grp, idp$gui$win, enablePlotLabel=FALSE, enableMenuButtons=FALSE, startWithTab=FALSE,
                       plotObjLoadHandler=function(obj) IDP.loadIsodatFileTab(idp, obj$plotinfo),
                       plotEventHandlers=list(
                          Changed = function(h,...) IDP.plotClickHandler(idp, h),
                          Doubleclick = function(h,...) IDP.plotDoubleClickHandler(idp, h),
                         Rightclick = function(h,...) IDP.plotRightClickHandler(idp, h))) 
    
  ### table grp
  tag(idp$gui$win, "dataTable") <- gtable(IDP.getEmptyPeakTable(idp), expand=TRUE, cont=tag(idp$gui$win, "tableGrp"))
  
 

  
  ### initialize file browser (this late so it has access to the different objects created later)
  fileBrowser.gui()

  ### make window visible after it's completely initialized
  optionsSwitch(modeacts, modeact_IDs, list(name=idp$settings$mode)) # select right option from the start
  optionsSwitch(xaxisActs, xaxisSignals, list(name=idp$settings$plotOptions$xUnits$ids[[idp$settings$plotOptions$xUnits$value]])) # select right xaxis from the start
  
  visHandler <- addHandlerFocus(idp$gui$win, handler=function(...) {
    ### starting plot and notebook positions
    visible(idp$gui$info.graph) <- TRUE
    plot.new()
    text(0, 0, " ")
    svalue(idp$gui$fileInfo.nb) <- 1
    addHandlerChanged(idp$gui$fileInfo.nb, handler=function(h,...) if (h$pageno ==2) IDP.plotRefs(idp))
    
    ### divider positions
    svalue(idp$gui$gl)<-IDP.getSettings(idp, "leftPane")
    svalue(idp$gui$gr)<-IDP.getSettings(idp, "rightPane")
    svalue(idp$gui$gall)<-IDP.getSettings(idp, "centerPane")
    
    # block Handler (only want it to fire once)  
    blockHandler(idp$gui$win, ID=visHandler)
  })
  
  visible(idp$gui$win)<-TRUE # window initially invisble to make plotting right away possible (without the margins error)
  return (idp)
}

#FIXME: move all data related things to a data menu
#FIXME: move plot manipulation to plot menu
#FIXME: add menu item for copy peak table (to make shortcut work)
# get toolbar and navigation structure
IDP.getNavXML<-function() {
  ### menu and toolbar navigation structure
  nav.xml<-'<ui>
    <menubar name="menubar">
  <menu name = "IDP" action="IDP">
  <menuitem action="SaveToWorkspace" />
  <menuitem action="Help"/>
  <menuitem action="Quit" />
  </menu>
  <menu name ="FileMenu" action ="File">
    <menuitem action ="OpenFile" />
    <menuitem action ="CloseFile" />
    <menuitem action ="CloseAll" />
  </menu>
  <menu name="View" action="View">
    <menuitem action="ZoomBack"/>
    <menuitem action="ZoomFull"/>
    <menuitem action="ZoomIn"/>
    <menuitem action="ZoomOut"/>
    <menuitem action="BestFit"/>
    <menuitem action="MoveIntervalB"/>
    <menuitem action="MoveIntervalF"/>
    <menuitem action="SetAxes"/>
    <separator/>
    <menuitem action="FullScreen"/>
  </menu>
  <menu name="PlotMenu" action="Plot">
     <menu name="XUnits" action="XUnits">
        <menuitem action="XaxisSec"/>
        <menuitem action="XaxisMin"/>
    </menu>
    <menu name="PlotOptions" action="PlotOptions">
        <menuitem action="MarkRefs"/>
    </menu>
    <separator/>
    <menu name="Mode" action="Mode">
      <menuitem action ="ModeInfo"/>
      <menuitem action ="ModeAdd"/>
      <menuitem action ="ModeEdit"/>
      <menuitem action ="ModeRefs"/>
    </menu>
    <menuitem action ="DeletePeak"/>
    <separator/>
    <menuitem action="SavePlot"/>
    <menuitem action="SaveAll"/>
    <separator/>
    <menuitem action="PrintPlot"/>
  </menu>
  <menu name="DataTable" action="DataTable">
    <menuitem action ="CopyTable"/>
    <menuitem action="TableColumns"/>
    <separator/>
    <menuitem action ="ExportExcel" />
    <menuitem action ="ExportAll" />
  </menu>
  <menu name="Settings" action="Settings">  
    <menuitem action="EditSettings"/>
  </menu>
  </menubar>
  <toolbar name ="toolbar">
    <toolitem action = "ZoomFull"/>
    <toolitem action = "ZoomIn"/>
    <toolitem action = "ZoomOut"/>
    <toolitem action = "BestFit"/>
    <toolitem action = "MoveIntervalB"/>
    <toolitem action = "MoveIntervalF"/>
    <toolitem action ="SetAxes"/>
    <separator/>
    <toolitem action ="ModeInfo"/>
    <toolitem action ="ModeAdd"/>
    <toolitem action ="ModeEdit"/>
    <toolitem action ="DeletePeak"/>
    <toolitem action ="ModeRefs"/>
    <separator/>
    <toolitem action ="CopyTable"/>
    <toolitem action ="Recalculate"/>
    <toolitem action ="Revert"/>
  </toolbar>
  </ui>'
  return(nav.xml)
}
